//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RV_ArticelPictures
    {
        public int ID { get; set; }
        public string picture { get; set; }
        public Nullable<int> articleId { get; set; }
    
        public virtual RV_articles RV_articles { get; set; }
    }
}
