//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DATA.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class RV_ChatWineryUser
    {
        public int id { get; set; }
        public int wineryId { get; set; }
        public string fromemail { get; set; }
        public string toEmail { get; set; }
        public string text { get; set; }
        public Nullable<System.DateTime> dateTime { get; set; }
    }
}
